#!/usr/bin/env python

import random
import subprocess
import sys

ifc = sys.argv[1]

address = ':'.join(["%0.2x" % (random.getrandbits(8) & 254)] + ["%0.2x" % random.getrandbits(8) for i in range(5)])
print(address)

subprocess.call(
	"sudo ifconfig %s ether %s" % (ifc, address),
	shell=True,
)

ifco_output = subprocess.check_output("ifconfig {}".format(ifc), shell=True)

actual_mac = None

for line in ifco_output.split("\n"):
	if "ether" in line:
		line = line.strip() # entfernt whitespace
		actual_mac = line.split(" ")[1]

print("Should: {} Is: {}".format(address, actual_mac))