# Path to your oh-my-zsh installation.
export ZSH=$HOME/.config/zsh/oh-my-zsh

# colors
ZSH_THEME="sq3"

# history
HIST_STAMPS="yyyy-mm-dd"
plugins=(git git-flow vagrant)

source $ZSH/oh-my-zsh.sh

# alias
alias t='/tmp/tmp'
alias repos='~/repositories'
alias speedtest='/usr/local/bin/speedtest_cli'
alias pastebin='/usr/local/bin/pastebinit'
alias enterenv='. env/bin/activate'
alias v='/usr/bin/vim -p'
alias hs='history | grep'

alias g='git'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git pull'
alias gf='git fetch'
alias glog='git log --graph --color=always --all --pretty=format:"%C(auto)%h%d %s (%Cred%an, %ai)"'
alias gs='git status'

alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias notes='~/Documents/notes/'
alias pw='pwgen 15 1 -s -y | tr -d '\n' | pbcopy'
alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
alias w='wunderline'
alias l='ls -lahtr --color=auto --time-style="+ %F   %H:%M │ "'
alias ls='ls --color=auto'
alias lsr='ls_recent'
alias f='find . -iname'
alias play='mpv -fs --autosync=4 --cache=yes --cache-secs=60'
alias vm='cd ~/repositories/privat/vagrantfiles'
alias vb='VBoxManage'

# environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR='vim'

export PATH=/bin:$PATH
export PATH=/sbin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=~/repositories/private/env/bin:$PATH
export PATH=~/repositories/private/env/etc/mutt/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH

# man page
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export MANWIDTH=75

man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[0;37;102m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[4;32m") \
        PAGER=/usr/bin/less \
        _NROFF_U=1 \
        PATH=${HOME}/bin:${PATH} \
    man "$@"
}

# docker
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/iMarc/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

# dircolors
eval $(dircolors ~/.config/bash/dircolors-solarized/dircolors.256dark)

